version: '3.7'
services:
  orbit:
    image: orbit
    container_name: orbit
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orbit.rule=Host(`orbit.msmetko.xyz`)"
      - "traefik.http.routers.orbit.entrypoints=websecure"
      - "traefik.http.routers.orbit.tls=true"
      - "traefik.http.routers.orbit.tls.certresolver=le"
      - "traefik.http.services.orbit.loadbalancer.server.scheme=http"
      - "traefik.http.services.orbit.loadbalancer.server.port=6090"
      - "traefik.docker.network=traefik_default"
    expose:
      - "6090"
    command:
      - "serve"
      - "dist"
      - "-p"
      - "6090"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
