name: deploy on production
on:
  # Deploy only when pushed directly to the master
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: MAIN_ENV
    steps:
      - name: Scaling lamp
        uses: InCogNiTo124/scaling-lamp@master
        with:
          vault-password: ${{ secrets.VAULT_PASSWORD }}
